### ISSUE TITLE
Support Raspberry Pi 5 PWM and GCLK 

### ISSUE THREAD

**Issue by mstroh76** [GrazerComputerClub/WiringPi#21]

**Comment by mstroh76** [comment]
PWM configuration register is outside of gpiomem0, we need global RP1 memory access, issue  #22 to support

**Comment by mstroh76** [comment]
unsure if GCLK is supportable, maybe use special PWM configuration (with 50% duty)
RP1 support 4 pwm (BCM only 2), most likely we make new Interfaces to support all RP1 pwm features later.
This issue will try to make a full BCM compatible functionality.
**But this will only work with root access :-(**

**Comment by DanyPell** [comment]
Looking forward to support.

**Comment by mstroh76** [comment]
Issue moved to https://github.com/WiringPi/WiringPi/issues/258
